-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.movies
(
    movie_id serial NOT NULL,
    title character varying,
    genres_id bigint,
    PRIMARY KEY (movie_id)
);

CREATE TABLE IF NOT EXISTS public.links
(
    link_id serial NOT NULL,
    movie_id bigint NOT NULL,
    imdb_id bigint,
    tmdb_id bigint,
    PRIMARY KEY (link_id)
);

CREATE TABLE IF NOT EXISTS public.ratings
(
    rating_id serial NOT NULL,
    user_id integer NOT NULL,
    movie_id bigint,
    rating double precision,
    create_date bigint,
    PRIMARY KEY (rating_id)
);

CREATE TABLE IF NOT EXISTS public.tags
(
    tag_id serial NOT NULL,
    user_id bigint,
    movie_id bigint NOT NULL,
    tag character varying,
    create_date bigint,
    PRIMARY KEY (tag_id)
);

CREATE TABLE IF NOT EXISTS public.genres
(
    genres_id serial NOT NULL,
    genres1 character varying,
    genres2 character varying,
    genres3 character varying,
    genres4 character varying,
    genres5 character varying,
    genres6 character varying,
    genres7 character varying,
    movies_id bigint NOT NULL,
    PRIMARY KEY (genres_id)
);

ALTER TABLE public.links
    ADD FOREIGN KEY (movie_id)
    REFERENCES public.movies (movie_id)
    NOT VALID;


ALTER TABLE public.tags
    ADD FOREIGN KEY (movie_id)
    REFERENCES public.movies (movie_id)
    NOT VALID;


ALTER TABLE public.ratings
    ADD FOREIGN KEY (movie_id)
    REFERENCES public.movies (movie_id)
    NOT VALID;

END;